Update Tracker.py
If self._get_field('level') is None, trying to convert it into int will crash the system :)

2024-12-23 14:22:46,232 Flask_server ERROR:Exception on /trackers [GET]
Traceback (most recent call last):
  File "/home/user/ail-framework/AILENV/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ail-framework/AILENV/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ail-framework/AILENV/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ail-framework/AILENV/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ail-framework/AILENV/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ail-framework/var/www/Role_Manager.py", line 81, in decorated_view
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ail-framework/var/www/blueprints/hunters.py", line 74, in trackers_dashboard
    trackers = Tracker.get_trackers_dashboard(user_org, user_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ail-framework/bin/lib/Tracker.py", line 785, in get_trackers_dashboard
    if not tracker.check_level(user_org, user_id):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ail-framework/bin/lib/Tracker.py", line 220, in check_level
    level = self.get_level()
            ^^^^^^^^^^^^^^^^
  File "/home/user/ail-framework/bin/lib/Tracker.py", line 183, in get_level
    level = int(self._get_field('level'))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'